<?php
$LOREM_ARRAY=array("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam pellentesque turpis et dapibus facilisis. Ut ullamcorper iaculis diam et eleifend. Praesent a ex euismod, pharetra eros in, malesuada diam. Nam egestas ex eget mattis accumsan. Quisque rutrum rutrum est, pellentesque blandit quam lobortis imperdiet. Ut ultrices sagittis metus at dignissim. Proin faucibus auctor porttitor. In tincidunt magna convallis tincidunt sagittis. Vestibulum vulputate ante sed neque gravida tristique. Phasellus in ornare mauris. Donec id massa quis ipsum interdum maximus. Suspendisse et eros nec orci tristique egestas.",
    "Cras dui quam, feugiat at nibh nec, mattis egestas tortor. Cras et imperdiet elit, et interdum nisi. Ut egestas scelerisque ex, nec faucibus erat pharetra non. Donec sodales magna sed ultrices fermentum. Mauris pulvinar rhoncus metus sit amet imperdiet. Phasellus ac semper lacus. In lacinia nec odio et aliquet. Nunc elementum enim vitae pretium vehicula. Nulla imperdiet sed lorem et elementum. Aenean ultrices non felis id aliquet. Aliquam id dolor eget arcu gravida euismod. Vestibulum orci ligula, auctor ac arcu lobortis, pharetra posuere libero. Nulla condimentum tempus justo, ut lacinia nisi accumsan nec.",
    "Nullam consequat mauris justo. Vestibulum scelerisque ornare eros, eget varius arcu suscipit sit amet. Vivamus aliquam quis purus et rhoncus. Donec nec pellentesque diam. Nam et venenatis ligula. Aenean vitae libero a sapien mattis congue vel id purus. Vivamus tincidunt vestibulum lacus, quis blandit magna malesuada non. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus eleifend sagittis leo, eget pharetra purus dictum vel. Nam porta ultricies quam, at laoreet sapien pellentesque eu. Sed molestie, dolor eget aliquet lobortis, mauris libero ultricies est, id volutpat tellus nibh imperdiet dolor. Morbi nunc diam, varius non elementum a, luctus ut sapien. Nullam erat quam, efficitur nec metus condimentum, pellentesque feugiat enim. Nam mollis purus nec dictum faucibus.",
    "In ullamcorper convallis nisi, et porttitor ipsum varius eu. Morbi non fringilla lorem. Pellentesque molestie magna turpis, sit amet suscipit mauris suscipit eget. Nulla at eleifend diam, quis dapibus arcu. Nullam pharetra interdum sem laoreet gravida. Integer sagittis et nunc eu scelerisque. Vestibulum interdum bibendum lectus ut ultrices. Sed ut scelerisque eros. Suspendisse viverra ex vitae felis ullamcorper cursus. Aenean pretium diam eget eros scelerisque sollicitudin. Nunc ac dolor et leo convallis cursus vel in augue.",
    "Sed iaculis tincidunt suscipit. Sed est nisi, hendrerit non hendrerit sed, placerat et mi. Donec quis ipsum pharetra, ullamcorper sapien vel, iaculis nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In tincidunt euismod malesuada. Duis imperdiet elit quis mauris scelerisque, quis porta enim eleifend. Etiam varius a nisi eu laoreet.",
    "Sed vel pharetra tellus. Donec lectus elit, laoreet in leo at, sagittis ullamcorper sem. Aenean vitae libero efficitur, congue leo sit amet, suscipit eros. Etiam maximus mi gravida, ullamcorper turpis quis, semper ante. Aliquam finibus ullamcorper velit, a placerat sapien consectetur sed. Proin eu sapien nec libero accumsan scelerisque ac vitae ligula. Vestibulum pulvinar sapien eros, id finibus nulla suscipit in. Nulla mi est, posuere eget nunc ut, placerat commodo est. Nunc rutrum ex vel mi accumsan, sed placerat neque feugiat. Vivamus porta risus nec sapien fringilla, ut pellentesque mauris tristique. Vivamus sodales suscipit tellus, nec consectetur metus viverra quis. Nulla lacinia ligula vel nisl vestibulum egestas. Nam volutpat a ligula et porta.",
    "Cras vitae ex a diam fermentum mattis nec vel quam. Phasellus efficitur, enim quis ultrices lacinia, odio lorem pellentesque arcu, at elementum augue libero vitae diam. Proin hendrerit congue justo, sed feugiat orci congue quis. Mauris vestibulum velit quis quam tempor, eget blandit arcu condimentum. Donec et malesuada elit. Vestibulum iaculis, mauris et venenatis ultricies, mauris ipsum imperdiet enim, sit amet interdum arcu erat nec dolor. Vestibulum in rhoncus mauris. Morbi congue nunc sit amet risus vehicula lobortis. Mauris volutpat neque elementum, maximus diam id, cursus magna. Maecenas nibh felis, scelerisque in pellentesque ac, consectetur eget diam. Donec ullamcorper porttitor ante, ut venenatis mauris congue non. Sed et dictum tellus. Nulla facilisi. Pellentesque venenatis risus augue, in aliquet elit condimentum nec.",
    "Donec laoreet augue vitae arcu euismod vulputate. Donec gravida, mauris non vestibulum cursus, odio ipsum efficitur mi, at ultrices ipsum ipsum at urna. Donec eget urna ut quam ultricies suscipit at vel nisi. Aenean iaculis massa vel mauris blandit commodo. Integer eget eleifend enim, ac cursus magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur cursus semper euismod.",
    "Maecenas non maximus nunc. Cras sagittis erat ac nunc iaculis ultricies. Ut laoreet nec elit quis finibus. Donec pretium odio a enim laoreet, a viverra lectus viverra. Fusce pulvinar, arcu a scelerisque accumsan, dolor massa suscipit arcu, sed ornare odio magna vel lectus. Integer elit dolor, tempus ultrices ante ac, faucibus semper justo. Vestibulum interdum, velit et consequat pretium, magna nulla blandit elit, eget ultricies ipsum felis sit amet massa. Etiam a rhoncus nunc, et mattis ligula. In in congue odio. Vivamus sed accumsan velit. Maecenas felis mauris, molestie vitae porttitor quis, eleifend quis enim. Nulla sit amet justo ac mi malesuada iaculis. Duis mauris enim, vestibulum non euismod at, ultrices sit amet erat. Aenean consequat dolor massa, sed auctor orci suscipit ut. Nulla id blandit tellus, sit amet gravida felis. Maecenas mauris ex, malesuada a massa vitae, placerat maximus nulla.",
    "Sed semper dolor ut diam rutrum, ut placerat ligula malesuada. Sed maximus imperdiet quam. Nam finibus sem ac ex volutpat, quis cursus lectus volutpat. Integer efficitur ut ligula a sagittis. Sed iaculis eu nisl non sollicitudin. Nam fermentum hendrerit eleifend. In consequat ex non purus bibendum ultricies. Integer diam velit, euismod ut consequat nec, condimentum ut nulla. Duis accumsan iaculis turpis, id iaculis elit euismod nec. Aliquam in magna pharetra, congue sem vitae, consequat lacus.",
    "Sed a venenatis dui. Maecenas dapibus ex in libero iaculis fermentum. Curabitur tellus quam, molestie quis commodo sed, maximus eget sem. Morbi finibus leo cursus tortor euismod congue. Quisque interdum nibh et ligula aliquam pharetra. Nulla dolor erat, rhoncus scelerisque malesuada id, maximus ac urna. Maecenas metus tortor, porta at urna in, varius tempor metus. Nullam porta sagittis orci, ut porta leo porttitor eget. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce ac nunc ac eros congue tristique ac at nulla. Pellentesque ac molestie nibh. Curabitur placerat et eros ut rhoncus. Praesent non fermentum nisi, ut lobortis tellus. Aenean ipsum lectus, scelerisque et nulla eu, ornare facilisis risus. Cras vel orci efficitur diam condimentum mollis id ut enim.",
    "Sed tempus tellus leo, ac varius magna pharetra eget. Proin vel nisi commodo ante suscipit sagittis ut a nibh. Donec at dolor tellus. Ut dictum mauris quam, eget suscipit nibh porttitor a. Donec ac nisi suscipit, condimentum mi non, sodales eros. Praesent vitae lacus vel justo maximus pretium id vitae ex. Aenean vel accumsan ligula, vel accumsan magna. Vivamus et accumsan odio. Vestibulum varius suscipit tellus in porttitor. Nunc tristique consequat egestas. Nulla molestie in lectus id congue.",
    "Proin sit amet mi nunc. In non felis velit. Mauris gravida euismod vulputate. Ut fringilla auctor pretium. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in bibendum orci. Nulla et nibh turpis. Morbi elit mi, tincidunt sed facilisis eget, eleifend nec nisi. Vivamus et velit quis mauris pharetra consectetur. Praesent id tristique dolor. Nulla facilisi. Donec at turpis sed mauris commodo consequat. Morbi posuere sagittis odio, sed placerat leo vehicula sed. Nullam maximus ornare tellus, sed cursus mi cursus quis. Quisque mi erat, molestie vel pulvinar non, auctor sed dui. Fusce tincidunt faucibus leo, eu maximus risus elementum nec.",
    "Nam dictum sit amet ante at aliquet. Pellentesque fringilla arcu vitae purus vestibulum, quis blandit ipsum finibus. Nulla mollis dui quis arcu euismod, in dictum urna lacinia. Fusce posuere blandit turpis vitae volutpat. Suspendisse dictum, lorem at pharetra hendrerit, augue leo congue nulla, in convallis est ante non lectus. Quisque tristique nulla nisi, vitae hendrerit metus interdum non. Donec non scelerisque libero. In pellentesque fringilla leo, a mattis nisi egestas vitae. Ut feugiat cursus tellus. Fusce lobortis, ex in viverra efficitur, libero arcu mollis est, sit amet varius nulla nisi id orci. Vestibulum quis dictum neque. Nullam porta interdum viverra. Sed pulvinar dolor turpis, non fermentum elit sagittis id. Cras maximus dolor et augue gravida, eu ullamcorper dolor pretium. Suspendisse viverra arcu sit amet leo ultrices congue. Aenean ultrices ipsum nisl, maximus malesuada turpis pellentesque at.",
    "Praesent quis orci quis enim semper consequat. Donec porta egestas lorem sed suscipit. Vestibulum vitae finibus lorem, et maximus metus. Suspendisse non fermentum massa, a bibendum purus. Proin ipsum elit, tempus eu leo et, posuere tempor tortor. Morbi malesuada nec purus non ornare. Sed lobortis, justo non lobortis facilisis, metus ipsum posuere justo, vitae aliquam mi urna vitae justo. In sed ipsum tellus. Pellentesque malesuada tellus nec maximus porttitor. Morbi ac varius ligula. Suspendisse gravida aliquam nulla id feugiat. Aliquam vitae urna condimentum, viverra massa in, sollicitudin dui. Etiam quis lorem rhoncus, eleifend elit sit amet, interdum turpis. Praesent bibendum posuere enim.",
    "Phasellus gravida maximus nunc, at blandit velit rhoncus id. In metus nisl, egestas a purus ut, pretium dictum magna. Integer tristique semper justo sed efficitur. In nunc tortor, vestibulum sit amet finibus facilisis, sagittis eget mauris. Nullam turpis sem, mollis eget nulla commodo, dignissim tempus dui. Nulla facilisi. Ut augue est, fringilla sodales justo eget, fringilla auctor sem. Duis euismod sagittis tempor. Etiam in tellus sit amet lacus tincidunt posuere quis sed justo. Pellentesque congue auctor molestie. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tristique eleifend est ac imperdiet. Donec metus quam, iaculis sed arcu at, rhoncus ultricies mi. Nunc egestas, massa sed pretium molestie, nulla velit bibendum nibh, et iaculis magna sem volutpat elit. Pellentesque mauris mauris, consequat et varius at, dictum eu felis. Duis sit amet odio sit amet orci dapibus fringilla nec ut neque.",
    "Nulla hendrerit, odio sed mollis volutpat, nunc risus venenatis purus, eget vulputate metus nibh nec metus. Aliquam sagittis eros vel dolor lacinia, et congue neque facilisis. Sed ut lacinia neque. Mauris vel dui ac eros consectetur dictum. Nam nec posuere nulla, egestas gravida tellus. Curabitur a leo quis ex dictum hendrerit. Sed consectetur nisi blandit tortor blandit, non aliquam arcu pulvinar.",
    "Nulla tincidunt a est ut maximus. Fusce ut ex fermentum, lobortis massa id, varius dolor. Proin maximus, nisl sit amet feugiat placerat, est nisi consectetur nulla, at hendrerit arcu est nec sapien. Mauris laoreet ullamcorper dolor id maximus. Nam ultricies libero ex, vel dignissim sem pulvinar quis. Nam elit purus, euismod id mi non, condimentum vulputate augue. Sed et libero dolor. Aenean sed molestie sapien. Ut vehicula sollicitudin dolor a malesuada. Aenean ultrices laoreet augue sit amet laoreet. Pellentesque facilisis sem eget diam pellentesque faucibus. Curabitur blandit lacus lectus. Curabitur sit amet dolor orci. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent lacinia magna et justo vehicula, a porttitor erat egestas. Quisque nec libero metus.",
    "Nunc euismod urna ultrices tortor feugiat, vel placerat velit volutpat. Sed quis feugiat urna. Phasellus dictum id eros et varius. Fusce nisi ex, cursus sit amet purus quis, faucibus luctus diam. Duis pellentesque urna quis felis tristique, ut pellentesque elit dictum. Sed ut fringilla quam, et rhoncus diam. Cras sit amet placerat massa, eget tempor dolor. Pellentesque eu ex in dui tempus suscipit at et mauris. Quisque efficitur semper finibus. Fusce consectetur arcu rutrum semper dignissim. Cras porttitor, ligula a luctus varius, nunc risus mattis ligula, vitae lobortis orci est sed enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam mi enim, auctor posuere bibendum commodo, consequat sed tortor. Vivamus at libero rutrum, commodo purus dapibus, vehicula dui. Sed leo tellus, ultrices eget lacus a, placerat tempus felis.",
    "Duis fringilla leo orci, id volutpat velit euismod nec. Nulla id tortor efficitur, accumsan nibh sit amet, tempor ipsum. Pellentesque non risus finibus, auctor lorem a, pretium mi. Duis id imperdiet lacus. Integer ullamcorper turpis nec mattis viverra. Fusce semper ipsum et mollis aliquam. Nunc leo lorem, posuere eu sollicitudin at, facilisis quis leo. Suspendisse ornare pharetra urna vitae suscipit. Sed tincidunt dui lectus, et vestibulum metus bibendum eu. Duis vulputate nisl id magna pellentesque, commodo lobortis erat ultrices. Maecenas lobortis eu augue nec feugiat. Pellentesque euismod urna sed sem sagittis vulputate hendrerit a libero. Quisque varius ultrices volutpat. Vivamus ut eros vitae lacus ultrices elementum. Aenean elementum volutpat eros, id pellentesque nisi hendrerit ac. Cras ut magna libero.",
    "Donec augue orci, pulvinar in eleifend at, sollicitudin vel massa. Ut tincidunt dui in nunc sagittis dignissim. Ut ut ex orci. Aenean vitae hendrerit sapien, in consectetur massa. Curabitur at arcu in leo pharetra rutrum. Proin elementum est vel dictum dictum. Ut faucibus lacus ac nulla congue, id efficitur mi porta. Nunc bibendum nec neque nec consectetur. Curabitur semper eget dui id aliquet. Curabitur vel risus in eros auctor placerat. Integer pellentesque faucibus faucibus. Donec sodales lacinia leo in dignissim. Nullam pretium ullamcorper odio, sit amet finibus augue faucibus at. Nullam semper metus quis ullamcorper tincidunt.",
    "Vestibulum rhoncus tincidunt sapien eu hendrerit. Pellentesque nec ex iaculis ex elementum rutrum. Phasellus a malesuada elit. Mauris facilisis nibh id mi efficitur tincidunt. Vivamus eu elit tincidunt, tincidunt velit quis, aliquam odio. Fusce ultrices tristique maximus. Maecenas malesuada leo eu lectus ornare luctus. Sed ut libero orci. Etiam at porttitor eros. Integer pellentesque pharetra arcu a venenatis. Mauris tincidunt velit eros, sed ullamcorper felis pharetra in. Suspendisse sollicitudin maximus sem, ut efficitur elit rhoncus vel.",
    "Sed imperdiet fringilla varius. Pellentesque iaculis semper quam, sed tincidunt justo ullamcorper id. Nunc euismod suscipit enim at feugiat. Curabitur convallis elit nec nisl eleifend, a tincidunt sem faucibus. Donec tincidunt laoreet varius. Donec pulvinar justo enim, mollis vehicula magna imperdiet vitae. Curabitur et ipsum vehicula purus dictum tincidunt sit amet a ligula. Suspendisse id odio at sem bibendum congue. Nullam rhoncus dignissim pulvinar. Vestibulum feugiat odio ac tellus consequat consectetur. Fusce euismod gravida elit, ut eleifend massa vehicula a. Duis eget laoreet nisl. Sed cursus dui quis eros egestas, a faucibus nisi sollicitudin.",
    "Donec efficitur, tellus id vehicula aliquet, urna ligula tincidunt augue, venenatis rutrum sapien leo eu dui. Morbi convallis sed nunc luctus ullamcorper. In nec dictum nulla. Donec quis urna viverra, lobortis ipsum sed, laoreet sapien. Fusce tempus, magna eu pulvinar fringilla, mauris ligula porttitor ligula, sed placerat mi nibh sed odio. Nulla iaculis elit nec arcu egestas faucibus. Fusce a lacus eu dolor iaculis faucibus.",
    "Nulla facilisi. Suspendisse luctus accumsan risus, sit amet tincidunt leo commodo vitae. Morbi ornare at odio tincidunt lobortis. Cras lacinia ante vitae eros pharetra, quis vestibulum magna maximus. Cras id pellentesque odio. Sed facilisis sit amet orci vel pharetra. Praesent turpis lorem, mattis in consectetur ac, tincidunt ut ante. Phasellus bibendum tortor nec vulputate ultricies. Nulla ornare, eros in bibendum ultrices, mi sapien imperdiet tortor, sed lobortis sem lectus condimentum augue. Etiam erat velit, finibus at sagittis in, iaculis eget sem. In id tincidunt nisl. Nullam iaculis nunc id malesuada lobortis. Nunc ut dolor sed felis euismod efficitur pretium ac odio. Mauris ut ante sem. Nulla mattis sapien et odio interdum aliquam.",
    "Nullam cursus nulla sit amet laoreet accumsan. Pellentesque sed nisi mauris. Praesent euismod sapien eu nisl elementum auctor. Maecenas pulvinar velit ex, non convallis orci auctor in. Sed ut pretium erat. Fusce ornare urna vitae turpis dignissim, eget aliquet neque suscipit. In nec arcu tincidunt, malesuada magna sit amet, ultrices tellus. Etiam mi arcu, fringilla sed iaculis sit amet, rhoncus in ante. Proin urna diam, dignissim eget semper euismod, viverra a ante.",
    "Mauris scelerisque et elit ac vestibulum. Mauris ac tincidunt metus, venenatis blandit mi. Cras sit amet tincidunt enim. Aenean rhoncus vulputate gravida. Aenean non interdum ipsum. Aliquam sed tellus molestie, commodo est nec, gravida metus. Suspendisse lobortis ligula nec magna suscipit, id ullamcorper urna consectetur. Mauris facilisis convallis pulvinar. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed vitae interdum mi, vitae posuere dui. Aliquam in hendrerit mauris. Maecenas interdum sollicitudin mauris et faucibus. Maecenas ac tincidunt eros. Maecenas augue nulla, lobortis non vulputate ac, hendrerit quis sem. Phasellus vitae lorem ut massa bibendum interdum sit amet semper odio.",
    "Quisque eget mauris pellentesque, accumsan risus id, sollicitudin nulla. Phasellus quam nulla, faucibus eu sollicitudin quis, rutrum ac est. Suspendisse sed efficitur tortor. Donec mattis nunc vel massa placerat accumsan. Pellentesque tincidunt sed ante ac laoreet. Fusce eget nulla leo. Morbi pretium congue urna, in cursus felis tempus sit amet. Nam lacinia eros id nibh consectetur semper. Vestibulum laoreet sapien ac nibh fermentum, eget iaculis purus lacinia. Duis quis efficitur ipsum. Cras lacinia odio velit, in dapibus lectus accumsan nec. Pellentesque a feugiat metus. Etiam sollicitudin vulputate massa rhoncus auctor. Suspendisse molestie mauris vitae aliquam malesuada.",
    "Nullam eget urna nec elit dignissim molestie. Aenean porta magna gravida, suscipit diam vel, dictum libero. Ut a nisi elit. Aliquam a porta ante. Pellentesque sagittis congue hendrerit. Phasellus ullamcorper ut lorem ac vestibulum. Integer mollis, urna a vestibulum pharetra, tellus tortor egestas risus, eu gravida magna sapien sit amet augue. Sed blandit metus malesuada luctus mattis. Maecenas tristique maximus dolor, et aliquam eros faucibus ac. Nulla pharetra dictum nunc, at semper nibh commodo nec. Fusce hendrerit venenatis leo, a maximus nisi posuere et. Pellentesque tempus ligula sagittis mauris volutpat, ut gravida dolor laoreet. Curabitur et libero enim. Vivamus nulla erat, iaculis in enim sit amet, finibus hendrerit velit. Integer aliquet tortor a euismod mattis. Integer ante augue, condimentum sed consequat in, pellentesque ac sem.",
    "In vulputate dui in tellus laoreet, id mattis lorem malesuada. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed eu orci eros. Donec varius volutpat ultricies. Nam at dui id nisl tempor consectetur quis sed elit. Nunc quis ipsum vel elit semper hendrerit. Integer tristique dui odio. Nullam felis neque, aliquet sit amet viverra id, viverra ac nisl. Praesent imperdiet pharetra velit, eget finibus urna convallis sed. Integer dignissim odio leo, at finibus sapien vestibulum luctus. Donec lorem risus, volutpat eget dui vel, tincidunt facilisis felis. Vivamus venenatis gravida turpis, quis sodales nisi laoreet et."
);

$number= $_POST('number');

for ($i=0, $i< $number ;$i++){
    $paragraphe= $LOREM_ARRAY;
    $paragraphe[]= $number[rand(0, count($LOREM_ARRAY)-1)]; 
    echo $paragraphe;
};

?>

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PHP (TEST)</title>
</head>
<body>

<form method="POST">
    <input type="number" max="30" min="1" name="number">
    <button type="submit" name="send">Générer</button>
</form>
<br>
<textarea name="generate" readonly="readonly"></textarea>

</body>
</html>